version: '2'

services:
    gateway:
        build:
            context: .
            dockerfile: GW.Dockerfile
        container_name: "gateway"
        ports:
            - "8080:80"
            - "8888:443"
        links:
            - api
            - gameplay
        depends_on:
            - api
            - gameplay
        environment:
            NODE_PORT: 5000
            NGINX_PORT: 80
            NGINX_SSL_PORT: 443
            NGINX_ACCESS_LOG: /var/log/access.log
            NGINX_ERROR_LOG: /var/log/error.log
            NGINX_DOCUMENT_ROOT: /var/www/html
            SERVER_NAME: dev.caro.local
    api:
        build:
            context: .
            dockerfile: Node.Dockerfile
        container_name: "api"
        ports:
            - "6000:5000"
        volumes:
            - ./www/html:/var/www/html:rw
        links:
            - redis
            - mongo
        depends_on:
            - redis
            - mongo
        environment:
            NODE_PORT: 5000
            SERVICE_INIT_SCRIPT: /var/www/html/init.sh
    gameplay:
        build:
            context: .
            dockerfile: Node.Dockerfile
        container_name: "gameplay"
        ports:
            - "7000:5000"
        volumes:
            - ./www/html:/var/www/html:rw
        links:
            - redis
            - mongo
        depends_on:
            - redis
            - mongo
        environment:
            NODE_PORT: 5000
            SERVICE_INIT_SCRIPT: /var/www/html/init.sh
    ui:
        build:
            context: .
            dockerfile: UI.Dockerfile
        container_name: "ui"
        ports:
            - "80:80"
            - "443:443"
            - "8000:8000"
            - "8800:8800"
        volumes:
            - ./www/html:/var/www/html:rw
        environment:
            NGINX_PORT: 80
            NGINX_SSL_PORT: 443
            NGINX_ACCESS_LOG: /var/log/access.log
            NGINX_ERROR_LOG: /var/log/error.log
            NGINX_DOCUMENT_ROOT: /var/www/html
            SERVER_NAME: _
            YARN_SERVICE_URL: http://127.0.0.1:8001
            NGINX_YARN_PORT: 8000
            NGINX_YARN_SSL_PORT: 8800
    redis:
        container_name: redis
        image: redis
        hostname: redis
        volumes:
            - ./data/redis:/data
        ports:
            - "6379:6379"
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/mongo:/data/db
        command: mongod --smallfiles --logpath=/dev/null # --quiet

